### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rsangole** [yixuan/sysfonts#10]
Hi yixuan,

Many thanks for putting the package together. It's quite useful.

What license are you intending for your package? I don't see a License file, so I don't know if you're MIT, or GPL or otherwise.

Could you help clarify?

Thanks!

**Comment by yixuan** [comment]
Hi @rsangole, it is GPL-2, given in the [DESCRIPTION](https://github.com/yixuan/sysfonts/blob/master/DESCRIPTION) file.
