### ISSUE TITLE
sysfonts not loading on macOS Catalina (10.15.4)

### ISSUE THREAD

**Issue by nmpeterson** [yixuan/sysfonts#11]
I am trying to use this package on macOS Catalina and receive the following error when attempting to load it:

```
> library(sysfonts)
Error: package or namespace load failed for ‘sysfonts’:
 .onLoad failed in loadNamespace() for 'sysfonts', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sysfonts/libs/sysfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/sysfonts/libs/sysfonts.so
  Reason: image not found
```

This is with R 3.6.2 and sysfonts 0.8 (fetched from https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/sysfonts_0.8.tgz).

**Comment by nmpeterson** [comment]
Hello @yixuan, are you still maintaining this package?

**Comment by yixuan** [comment]
Oops, somehow I didn't notice this issue report. I guess this is similar to this issue: https://github.com/yixuan/showtext/issues/13, and the potential solution is to install XQuartz.

**Comment by nmpeterson** [comment]
Thank you, that fixed the issue!

Would you consider updating the package to check for this particular error on load and suggest the user install XQuartz if it occurs? It seems that Apple stopped including XQuartz/X11 with macOS after version 10.7.

**Comment by yixuan** [comment]
Yeah, but unfortunately I do not have a Mac to test. Basically this is a problem of lacking the FreeType library. I guess the function of XQuartz is to provide FreeType, but maybe you can also install FreeType separately.

**Comment by nmpeterson** [comment]
FreeType is available as a [Homebrew formula](https://formulae.brew.sh/formula/freetype) (but I have not tested loading `sysfonts` with just FreeType and not XQuartz).

**Comment by gadenbuie** [comment]
I just went through something equivalent to this issue setting up GitHub actions to test [xaringanthemer](https://github.com/gadenbuie/xaringanthemer/) and can report that freetype without xquartz does not work. Seems like the official solution should be

```
brew cask install xquartz
```

**Comment by yixuan** [comment]
@gadenbuie Have you also checked the presence of `libpng`?

**Comment by gadenbuie** [comment]
@yixuan No I didn't, but in the CI run confirming that `libfreetype` was already installed I got the same error:

```
.onLoad failed in loadNamespace() for 'sysfonts', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/runner/runners/2.168.0/work/_temp/Library/sysfonts/libs/sysfonts.so':
  dlopen(/Users/runner/runners/2.168.0/work/_temp/Library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Users/runner/runners/2.168.0/work/_temp/Library/sysfonts/libs/sysfonts.so
  Reason: image not found
```

I bet there's a way to fix this by symlinking the installed `libfreetype.6.dylib` into the right place, but honestly `brew cask install xquartz` seems easier, especially to enable the `quartz()` device in RStudio.

**Comment by nmpeterson** [comment]
Shouldn't that be `brew cask install xquartz`?

**Comment by gadenbuie** [comment]
@nmpeterson Yes! Thanks for the catch, I updated my comment above

**Comment by yixuan** [comment]
OK, thank you for your help. @nmpeterson @gadenbuie 
I will update the README of `showtext` in the next release to remind users of this potential issue.
