### ISSUE TITLE
Cache Google Fonts

### ISSUE THREAD

**Issue by thomas-neitmann** [yixuan/sysfonts#12]
First of all, thank you for creating this superb package!

The `font_add_google()` function is extremely useful. However, from looking at the source it seems that the fonts are saved in a temporary directory. Thus, in every new `R` session I have to run `font_add_google()` again. This is quite undesirable as downloading the fonts takes a couple of seconds. In addition, if I run for example `font_add_google("Fira Sans")` twice in the same `R` session the font will be downloaded 2 times.

I feel that permanently saving the downloaded Google fonts would be a very useful feature. Inside `font_add_google()` you could then look if the requested font has already been downloaded and if so just call `font_add()` directly.

What do you think @yixuan?

**Comment by yixuan** [comment]
Thanks for the comments. I think an easy way to do this is to download the fonts you use frequently into your own directory, and then use `font_add()` to load them.

Check out the [gfonts](https://github.com/dreamRs/gfonts) package, which provides the `setup_font()` function that does exactly what you need.

**Comment by thomas-neitmann** [comment]
This is basically what I did but from a user perspective it would be much more convenient if `{sysfonts}` would do this automatically without me having to worry about it. An easy implementation would be to download the fonts to `System.file("fonts", package = "sysfonts")` and every time `font_add_google()` is called look in this directory if the font has already been downloaded.

I'd be more than happy to create a pull request for this feature. I am convinced that this would enhance the package.

**Comment by yixuan** [comment]
I see. Maybe this can be implemented with the (rarely known) [`font_install()`](https://github.com/yixuan/showtextdb/blob/master/R/font_install.R) function in the [`showtextdb`](https://github.com/yixuan/showtextdb) package.

The idea is that local fonts will be installed to the `showtextdb/fonts` folder (you need to have write access, of course). Every time `showtext` is loaded, it will search this folder and add the local fonts. To use this function one needs to provide a description of the font, which is basically the URLs of the font faces. I'll think about this later.

**Comment by yixuan** [comment]
I have updated the [showtextdb](https://github.com/yixuan/showtextdb) package and now you should be able to do something like this:

```r
library(showtext)
font_install(google_fonts("Open Sans"))
font_install(google_fonts("Fira Sans"))
font_families()
```

```
## [1] "sans"         "serif"        "mono"         "wqy-microhei" "Fira Sans"   
## [6] "Open Sans"   
```

The fonts are installed to the `fonts` folder in the `showtextdb` package, and will be automatically loaded when you use `showtext`.

Feedback is appreciated. :smiley:

**Comment by thomas-neitmann** [comment]
I just tested it and it works exactly as I wished. Thanks a lot for implementing this!

One thing that I found a bit strange was the message that got printed when installing the font, e.g.

```r
> font_install(google_fonts("Open Sans"))
downloading the 'regular' font face...
 [0%] Downloaded 0 bytes...
downloading the 'bold' font face...
 [0%] Downloaded 0 bytes...
downloading the 'italic' font face...
 [0%] Downloaded 0 bytes...
downloading the 'bolditalic' font face...
 [0%] Downloaded 0 bytes..
```
This doesn't look particularly informative to me.

In addition, I am now wondering if there's still a need for the `font_add_google()` function? It seems both `font_add_google("font")` and `font_install(google_fonts("font"))` make the font available for `{showtext}` but the latter has the obvious advantage of permanently saving the fonts.

**Comment by yixuan** [comment]
The message is produced by `curl`, and I'm not sure why it shows 0 bytes. You can check the actual sizes of the files.

`font_add_google()` is still needed for three reasons:
1. The font installed to `showtextdb` is a just a "cache", because it will be removed every time you upgrade or re-install `showtextdb`.
2. I cannot assume that all users have write permissions to the `fonts` directory, for example the packages may be installed by admins.
3. Some people including me may prefer a "clean" solution to the font problem, meaning that the fonts only exist in a temporary folder and do not modify the user directories.
