### ISSUE TITLE
add font_path to mac os path

### ISSUE THREAD

**Issue by drmowinckels** [yixuan/sysfonts#13]
Hi.

You should likely include the system font path to the macOS paths as a default location for macos fonts:

`/System/Library/Fonts` 

so that `font_paths()` on a mac would return:

`"/System/Library/Fonts"  "/Library/Fonts "  "~/Library/Fonts"`

**Comment by yixuan** [comment]
Thanks for the information. I do not have a Mac and your suggestion would be helpful. I'll add it in the next release.

**Comment by yixuan** [comment]
The path has been added in https://github.com/yixuan/sysfonts/commit/744430f4c6216b3b28cbf8cc5e9e99b02a34d96e, and the new version is going to CRAN soon.
