### ISSUE TITLE
configure line 2834 will fail in POSIX shells

### ISSUE THREAD

**Issue by Wesley-Chan** [yixuan/sysfonts#14]
In POSIX shells you use a single equation mark to compare two strings, while in bash you can use a single or double one.

You used a double one which only works in bash, but the shebang line tells us to run in sh.

Please change those double equation marks to single ones to provide better compatibility.

Thank you.

**Comment by yixuan** [comment]
Thank. It has been fixed in https://github.com/yixuan/sysfonts/commit/844dbae94ae123af282206d0fbb9b0362558d0a2.
