### ISSUE TITLE
Debug Compile Path (M1 cannot find libpng)

### ISSUE THREAD

**Issue by YourEconProf** [yixuan/sysfonts#18]
I use R on two machines: an M1 Mac mini and an Intel-based MacBook. The intel machine runs all just fine. Recently, I upgraded the M1 to 4.1 and I can no longer install sysfonts, which is critical for me, as the compilation cannot find libpng. I've installed libpng both from the R repository and via Homebrew. I don't expect anyone to walk me through this, but if someone could at least help me figure out where R is looking for the libpng libraries (and pkgconfig) that it is not finding, I should be able to handle from there.

```
* installing *source* package ‘sysfonts’ ...
** package ‘sysfonts’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... clang -arch arm64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang -arch arm64 accepts -g... yes
checking for clang -arch arm64 option to accept ISO C89... none needed
checking for pkg-config... no
checking for deflate in -lz... yes
checking for png_init_io in -lpng... no

****************************************************
Error: libpng not found. 
```

**Comment by collinschwantes** [comment]
Currently working through this as well. Issue  #17 may help. I am going to try forking the repo and changing the `configure` file to see that resolves the issue.

**Comment by collinschwantes** [comment]
@Youreconprof Tried changing the `configure` file in the only place I could find `opt/bin` but that failed to resolve the issue.

**Comment by yixuan** [comment]
Hi @YourEconProf @collinschwantes, can you install both `pkg-config` and `libpng` via Homebrew, and try the current version of `sysfonts` on Github?

**Comment by malcolmbarrett** [comment]
I tried installing those via Homebrew then used the dev version of the package, but unfortunately, it did not work for my M1 machine

**Comment by yixuan** [comment]
@malcolmbarrett I updated a new version to CRAN, and it will provide the binary package for Mac M1 in a few days. You may try to directly install `sysfonts` from CRAN when it's ready. `showtext` is also on the way.

**Comment by malcolmbarrett** [comment]
Thanks, I'll give that a try when the binaries are up!

**Comment by malcolmbarrett** [comment]
Installing the binaries straight from CRAN now works for me, FYI. Thanks!

**Comment by yixuan** [comment]
Great to hear that!

**Comment by JavOrraca** [comment]
> Hi @YourEconProf @collinschwantes, can you install both `pkg-config` and `libpng` via Homebrew, and try the current version of `sysfonts` on Github?

After updating to R 4.1.3, I encountered the same issue on my new M1 MacBook Pro for `sysfonts` 0.8.8 - FWIW, when `sysfonts` 0.8.5 was initially installed on my M1 Mac running R 4.1.2, I did not encounter this issue. The solution was to install `pkg-config` and `libpng` via Homebrew, thank you @yixuan and @malcolmbarrett
