### ISSUE TITLE
libpng not found

### ISSUE THREAD

**Issue by neilpanchal** [yixuan/sysfonts#2]
I am getting the following error during install:
```
****************************************************
Error: libpng not found.
If you have not installed libpng, you can download
the source code from http://www.libpng.org/

In Debian/Ubuntu-like systems, you can use
  "sudo apt-get install libpng12-dev"
to install libpng

For rpm-based systems, try
  "sudo yum install libpng-devel"
****************************************************
```

I am running Mac OS Sierra and I checked if `libpng` is installed. It is installed automatically as dependency with `R` and if I try to uninstall it through `brew`, I get the following message:

```
Refusing to uninstall /usr/local/Cellar/libpng/1.6.29
because it is required by r 3.3.3_1, which is currently installed.
```

So, it appears that `R` is finding `libpng` but the installer for `sysfonts` isn't finding it. Any ideas?

**Comment by yixuan** [comment]
Hi @neilpanchal, part of the reason is that `sysfonts` uses the `pkg-config` program to locate the libpng library. You can install `pkg-config` first and then have a second try.

**Comment by yixuan** [comment]
I choose to close this issue at this moment.

**Comment by Aliktk** [comment]
here below in my problem how to install PNG12 and MNG libraries please ans
Setting up FSL software...
[OK] User profile updated with FSL settings, you will need to log out and back in to use the FSL tools.
To use FSLView please install the PNG12 and MNG libraries with: sudo yum install libpng12 libmng
[fsluser@localhost tmp]$ install libpng12 libmng
install: cannot stat ‘libpng12’: No such file or directory

**Comment by MattCowgill** [comment]
I am encountering this same issue on arm64 Mac. I have libpng and pkg-config both installed.

**Comment by yixuan** [comment]
@MattCowgill May be this method can help you: https://github.com/yixuan/sysfonts/issues/17#issuecomment-857975652.
