### ISSUE TITLE
Unable to load font when a proxy is required

### ISSUE THREAD

**Issue by Sdurier** [yixuan/sysfonts#3]
The function `download_font_file` has no parameter for specifying a handle to pass to the underlying function `curl::curl_download`.
It's a problem when a proxy is needed.
For example :
> font.add.google("Gochi Hand", "gochi")
Error in curl::curl_download(url, dest) : Timeout was reached

I'm under windows and if i modify the function `download_font_file`, it works :
  proxy <- curl::ie_get_proxy_for_url(url)
  h <- curl::new_handle(verbose = F, proxy = proxy)
  curl::curl_download(url, dest, handle = h)
> (font.add.google("Gochi Hand", "gochi"))
[1] "sans"         "serif"        "mono"         "wqy-microhei" "gochi"

Sdurier

**Comment by yixuan** [comment]
I see. I didn't take proxies into account when I wrote the package. Would you like to submit a quick PR on this?

**Comment by yixuan** [comment]
Closed by #4 .
