### ISSUE TITLE
library时报错

### ISSUE THREAD

**Issue by shorpenlee** [yixuan/sysfonts#6]
载入需要的程辑包：sysfonts
Error: package or namespace load failed for ‘sysfonts’:
 loadNamespace()里算'sysfonts'时.onLoad失败了，详细内容：
  调用: dyn.load(file, DLLpath = DLLpath, ...)
  错误: 无法载入共享目标对象‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so’：:
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so
  Reason: image not found
错误: 无法载入程辑包‘sysfonts’

请问，library时如图所示的报错是为什么？我已经删除过包然后再重新装，或者调整安装路径 都无解。求回复！r是3.4.2

**Comment by yixuan** [comment]
你试一下这里面提到的方法安装XQuartz：https://github.com/yixuan/showtext/issues/13

**Comment by shorpenlee** [comment]
十分感谢了！！！祝好！
