### ISSUE TITLE
request: add libfreetype6-dev in SystemRequirements field

### ISSUE THREAD

**Issue by bagasbgy** [yixuan/sysfonts#9]
I've got installation error due to missing libfreetype6-dev library. I've noticed this error when I try to build a docker image using dockerfile generated from [`containerit`](https://github.com/o2r-project/containerit), which check system dependencies from DESCRIPTION file.

Please add it to SystemRequirements if you don't mind, thanks.

**Comment by yixuan** [comment]
Hi, FreeType is indeed in the system requirement (https://github.com/yixuan/sysfonts/blob/master/DESCRIPTION#L14). The reason is that R does not have a clear format for this field, so it is not meant to be parsed by programs.
